### PR TITLE
Temporary allow 3.0

### PR DESCRIPTION
**Pull request by cleentfaar**
Hey man! How's life 😄 ?

By temporary allowing this we can upgrade our symfony application in smaller steps from 3 to 4 (and eventually 5).
We can do another PR once we have reached the latest version to clean this up again for you.

Thanks!

### CODE REVIEW

**Comment by fieg** [comment]
Hey Cas 👋, Nice to see you! PR LGTM

**Comment by cleentfaar** [comment]
awesome! could you also do a new release?

**Comment by fieg** [comment]
I added you as a collaborator, so you can create releases as you see fit.

**Comment by cleentfaar** [comment]
Ah that's even better of course! But am I missing something; I don't see a new release button where I expect it? https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository#creating-a-release

Afaik I need write permissions for that (not just collab)? https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-releases

**Comment by fieg** [comment]
Github says your invitation is still pending. Guess you should have an email with an invite.

**Comment by cleentfaar** [comment]
... 🤦 

I miss this, don't you? 😂 

Thanks again!

**Pull request merged**
